# Drift build configuration
targets:
  $default:
    builders:
      drift_dev:
        enabled: true
        options:
          skip_verification_code: false
          store_date_time_values_as_text: true
